<?php

/**
 * @file
 * Adding classes to blocks.
 */

use Drupal\Core\Url;

/**
 * Getting all the settings saved.
 */

function isSettingIsEnabled($setting){
	$config = \Drupal::config('optimized_meta.settings'); // get the saved elements
	$state = $config->get($setting);

	return ($state == 1 ? 1 : 0);
}

/**
 * Implements hook_preprocess_html().
 */
function optimized_meta_preprocess_html(&$variables){
	
	## Default noindex meta
	$noindex = [
            '#tag' => 'meta',
            '#attributes' => [
                'name' => 'robots',
                'content' => 'noindex',
            ],
        ];
		
	$current_path = Url::fromRoute('<current>')->toString(); // get the current url page (not absolute)

	
	if($current_path == '/user/login' && isSettingIsEnabled('no_index_login'))
		$variables['page']['#attached']['html_head'][] = [$noindex, 'noindex'];
	
	if($current_path == '/user/register' && isSettingIsEnabled('no_index_register'))
		$variables['page']['#attached']['html_head'][] = [$noindex, 'noindex'];
	
	if($current_path == '/user/password' && isSettingIsEnabled('no_index_password'))
		$variables['page']['#attached']['html_head'][] = [$noindex, 'noindex'];

}